version: "3.8"

services:
  frontend:
    ports:
      - "4200:80"
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
  backend:
    ports:
      - "8000:8000"
    build:
      context: ./backend
      dockerfile: ./Dockerfile